### ISSUE TITLE
Headings: Inconsistent Use of Initial Uppercase and Lowercase Letters

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st430-12#12]
There is inconsistent use of uppercase and lowercase letters in headings. It should be consistent, and extend to template headings including:
- Normative references/Normative references
- Terms and definitions/Terms and definitions
- Additional elements/Additional Elements

We should standardize across all documents.

**Comment by SteveLLamb** [comment]
The tooling already conforms to ISO as:

- Normative references
- Terms and definitions
- Additional elements

If documents are not having this, the tooling should be updated. I don't the issue on this document.
