### ISSUE TITLE
6.2.2, Table 3 (PDF Only): Missing Row

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st430-12#24]
In the PDF, Table 3 is missing Row 6.
HTML version:
![image](https://github.com/SMPTE/st430-12/assets/118845840/8e90fe98-6f82-4bbc-af81-b3a2838ef971)

PDF version:
![image](https://github.com/SMPTE/st430-12/assets/118845840/46e2d353-7b21-44ec-b1be-a07990bf76ad)

The row specifying Edit Rate 60/1 is missing from the PDF.

**Comment by SteveLLamb** [comment]
@ERyan71258 this looks to have been resolved in https://github.com/SMPTE/st430-12-private/releases/tag/20230912-pub, correct?

**Comment by ERyan71258** [comment]
Yes, it was resolved, thanks.
